version: '3.8'

services:
  postgres-order:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - order-network

  catalog-postgres:
    image: postgres:15
    container_name: catalog-postgres
    restart: always
    environment:
      POSTGRES_DB: catalog-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data
    networks:
      - order-network

volumes:
  postgres_order_data:
  catalog_pgdata:

networks:
  order-network:
    driver: bridge
